language: c

os: linux

compiler:
  - clang
  - gcc

addons:
  apt:
    packages:
    - cpanminus

install:
  - git clone https://github.com/nginx/nginx.git  ../nginx
  - git clone https://github.com/nginx/nginx-tests.git  ../nginx-tests
  - sudo cpanm -v --notest Test::Nginx

script:
  - ls -ltra
  - cd ../nginx
  - ls -ltra
  - ./auto/configure --prefix=/tmp/nginx --add-dynamic-module=../ngx_http_waf_module --with-compat
  - make -j
  - make install
  - cd ..
  - ls -ltra
  - TEST_NGINX_BINARY=/tmp/nginx/sbin/nginx prove ./ngx_http_waf_module/t/waf.t
