language: c

os: linux

compiler:
  - clang
  - gcc

addons:
  apt:
    packages:
    - cpanminus

install:
  - git clone https://github.com/nginx/nginx.git
  - git clone https://github.com/nginx/nginx-tests.git
  - git clone https://github.com/vislee/ngx_http_waf_module.git
  - sudo cpanm -v --notest Test::Nginx

script:
  - cd ./nginx
  - ./auto/configure --prefix=/tmp/nginx --add-dynamic-module=../ngx_http_waf_module --with-compat
  - make
  - cd ..
  - TEST_NGINX_BINARY=/tmp/nginx/sbin/nginx prove ./ngx_http_waf_module/t/waf.t
